# SPDX-FileCopyrightText: Copyright DB Netz AG and the capellambse contributors
# SPDX-License-Identifier: CC0-1.0
rules:
  body-leading-blank: [2, always]
  footer-leading-blank: [2, always]
  scope-case: [2, always, lower-case]
  subject-case: [2, always, sentence-case]
  subject-empty: [2, never]
  subject-full-stop: [2, never, .]
  subject-max-length: [2, always, 72]
  type-empty: [2, never]
  type-enum: [2, always, [
      build,
      chore,
      ci,
      docs,
      feat,
      fix,
      merge,
      perf,
      refactor,
      revert,
      test,
    ]]
