# SPDX-FileCopyrightText: Copyright DB InfraGO AG
# SPDX-License-Identifier: CC0-1.0

name: Code QA

on:
  pull_request:
  push:
    branches: [master]
    tags: ["v*.*.*"]
  workflow_dispatch:
    inputs:
      wheel_build:
        type: boolean
        required: true
        description: Build wheels for all supported architectures

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref_type == 'tag' && github.sha || '0' }}
  cancel-in-progress: true

jobs:
  test:
    name: Test with Python ${{matrix.python_version}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python_version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        include:
          - os: ubuntu-24.04-arm
            python_version: "3.13"
          - os: windows-latest
            python_version: "3.10"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
          python-version: ${{matrix.python_version}}
      - name: Run unit tests
        run: uv run coverage run
      - name: Report coverage
        if: always()
        run: uv run coverage report

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
          python-version: "3.12"
      - name: Run Pre-Commit
        run: uv run pre-commit run --all-files

  build:
    name: Build wheel for ${{ matrix.target }} ${{ matrix.os }} (${{ matrix.interpreter || 'all' }}${{ matrix.os == 'linux' && ', ml=' || '' }}${{ matrix.os == 'linux' && (matrix.manylinux || 'auto') || '' }})
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'Wheel Build') || github.event.inputs.wheel_build == 'true'
    runs-on: ${{ matrix.os == 'linux' && 'ubuntu' || matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            manylinux: manylinux2014
            target: x86_64
          - os: linux
            manylinux: manylinux2014
            target: aarch64
          - os: linux
            manylinux: manylinux2014
            target: i686
          - os: linux
            manylinux: manylinux2014
            target: armv7
          - os: linux
            manylinux: manylinux2014
            target: ppc64le
          - os: linux
            manylinux: manylinux2014
            target: s390x

          - os: linux
            manylinux: musllinux_1_1
            target: x86_64
          - os: linux
            manylinux: musllinux_1_1
            target: aarch64

          - os: macos
            target: x86_64
          - os: macos
            target: aarch64

          - os: windows
            target: x86_64
          - os: windows
            target: i686
            python-architecture: x86
          - os: windows
            target: aarch64
            interpreter: 3.11 3.12 3.13
    env:
      CIBW_ENABLE: 'cpython-freethreading pypy'
      CIBW_BUILD_FRONTEND: 'build[uv]'
      CIBW_TEST_COMMAND: 'cd {project} && pytest tests -s'
      CIBW_TEST_COMMAND_WINDOWS: 'cd {project} & pytest tests -s'
      CIBW_ENVIRONMENT: 'PATH="$HOME/.cargo/bin:$PATH"'
      CIBW_ENVIRONMENT_WINDOWS: 'PATH="$UserProfile\.cargo\bin;$PATH"'
      CIBW_BEFORE_BUILD: |-
        pip install --break-system-packages -U setuptools-rust & ^
          rustup default nightly & ^
          rustup show
      CIBW_BEFORE_BUILD_LINUX: |-
        pip install --break-system-packages -U uv setuptools-rust &&
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=nightly --profile=minimal -y &&
          rustup show
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: ${{ matrix.os == 'windows' && matrix.target == 'i686' && 'x86' || 'x64' }}
      - run: pip install uv
      - name: Build and verify packages
        run: uvx cibuildwheel --output-dir dist/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{matrix.os}}
          path: dist/
          if-no-files-found: error
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    needs: [build, test, example-notebooks]
    if: startsWith(github.ref, 'refs/tags/v')
    environment:
      name: pypi
      url: https://pypi.org/project/capellambse
    permissions:
      id-token: write
    steps:
      - name: Download built wheels
        uses: actions/download-artifact@v4
        with:
          path: dist/
          pattern: wheels-*
          merge-multiple: true
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: Push to release branch
        continue-on-error: true
        env:
          GITHUB_REF: ${{github.ref}}
        run: |-
          releasever="$(echo "$GITHUB_REF" | grep -Po '(?<=^refs/tags/v)(?:0\.)?[1-9][0-9]*').x"
          if [[ "$releasever" = 0.5.x ]]; then releasever="${releasever%.x}"; fi
          git push origin "HEAD:release-$releasever"

  example-notebooks:
    name: Run and verify the example notebooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
          python-version: "3.12"
      - name: Run example notebooks
        run: |
          jq --version
          set -o pipefail
          export CAPELLAMBSE_UUID_SEED=0
          ok=true
          function celloutputs() {
            jq -r '.cells[] | select(.cell_type=="code") | .outputs[] | (.text, .data["text/plain"]) | .[]?' < "$1" |
              grep -v '^$' |
              sed -e 's/ at 0x[0-9a-fA-F]\+/ at 0x0/'
          }
          for file in docs/source/examples/*.ipynb; do
            old_outputs="$(celloutputs "$file")"
            if ! uv run --all-extras jupyter nbconvert --to notebook --execute "$file" --output "${file##*/}" --ExecutePreprocessor.timeout "${NOTEBOOK_TIMEOUT_SEC:-300}"; then
              ok=false
              continue
            fi
            new_outputs="$(celloutputs "$file")"
            diff -u3 <(echo "$old_outputs") <(echo "$new_outputs") || ok=false
          done
          $ok

  docs:
    name: Build documentation
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
          python-version: "3.12"
      - name: Install system-level dependencies
        run: sudo apt-get install -y pandoc
      - name: Auto-generate APIDOC sources
        run: make -C docs apidoc
      - name: Create docs
        env:
          SPHINXOPTS: ''
        run: make -C docs html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
